version: "3.9"
services:
  devenv:
    build:
      context: .
      args:
        - HOST_UID=${HOST_UID}
        - HOST_GID=${HOST_GID}
        - HOST_DOCKER_GID=${HOST_DOCKER_GID}
        - CONTAINER_USER=${CONTAINER_USER}
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/usr/bin/docker-compose:/usr/bin/docker-compose:ro"
      - "${SCRIPTS_DIR}:/home/scripts:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${CONTAINER_USER_HOMEDIR_MOUNT_PATH}:/home/${CONTAINER_USER}"
      - "${CONTAINER_USER_HOMEDIR_MOUNT_PATH}/.opt:/opt"
    command: tail -f /dev/null
    ports:
      - 8080:8080
