version: "3.9"
services:
  devenv:
    build: .
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/usr/bin/docker-compose:/usr/bin/docker-compose:ro"
      - "/home/dennis/devel/devenv/test:/home/devuser"
    command: tail -f /dev/null
